#!/bin/bash


curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
gunzip elm.gz
chmod +x elm
mkdir .local/bin
mv elm .local/bin/

python -m elm_kernel.install

echo "postBuild complete"